name: Analyze WinGo (Manual)

on:
  workflow_dispatch:
    inputs:
      limit:
        description: "Rows to load from Neon"
        required: false
        default: "20000"
      color_prob_threshold:
        description: "Min prob to alert"
        required: false
        default: "0.62"
      min_sources:
        description: "Min agreeing sources"
        required: false
        default: "2"
  # Uncomment to enable schedule later
  # schedule:
  #   - cron: "*/10 * * * *"  # every 10 minutes

concurrency:
  group: analyze-wingo
  cancel-in-progress: false

jobs:
  run-analyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run analyzer (alerts only on signals)
        env:
          NEON_CONN_STR: ${{ secrets.NEON_CONN_STR }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python analyze.py --source db --limit ${{ github.event.inputs.limit }} --enable_alert --color_prob_threshold ${{ github.event.inputs.color_prob_threshold }} --min_sources ${{ github.event.inputs.min_sources }}
