name: Analyze WinGo

on:
  workflow_dispatch:
    inputs:
      limit:
        description: "Rows to load from Neon"
        required: false
        default: "20000"
      color_prob_threshold:
        description: "Min prob to alert"
        required: false
        default: "0.60"
      min_sources:
        description: "Min agreeing sources"
        required: false
        default: "1"
  # 10-min schedule during awake hours only (IST 09:00–01:30)
  # IST 09:00 = 03:30 UTC start; run every 10 min until 20:00 UTC (01:30 IST)
  schedule:
    - cron: "30-59/10 3 * * *" # 09:00–09:50 IST (03:30, 03:40, 03:50 UTC)
    - cron: "*/10 4-19 * * *"  # 10:00–01:00 IST every 10 min
    - cron: "0 20 * * *"       # 01:30 IST final run

concurrency:
  group: analyze-wingo
  cancel-in-progress: false

jobs:
  run-analyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run analyzer (alerts only on signals)
        env:
          NEON_CONN_STR: ${{ secrets.NEON_CONN_STR }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LIMIT: ${{ github.event.inputs.limit || '20000' }}
          COLOR_PROB: ${{ github.event.inputs.color_prob_threshold || '0.60' }}
          MIN_SOURCES: ${{ github.event.inputs.min_sources || '1' }}
        run: |
          python analyze.py --source db --limit "$LIMIT" --enable_alert --log_to_db --color_prob_threshold "$COLOR_PROB" --min_sources "$MIN_SOURCES"
