name: WinGo Analysis

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:
    inputs:
      preset:
        description: "Signal frequency preset"
        required: false
        default: 'balanced'
        type: choice
        options:
          - conservative
          - balanced
          - aggressive
          - very_aggressive
      max_signals:
        description: "Max signals per run"
        required: false
        default: '3'
      enable_fast_mode:
        description: "Enable fast mode"
        required: false
        default: true
        type: boolean
      ignore_quiet_hours:
        description: "Ignore quiet hours (1-9 AM IST)"
        required: false
        default: false
        type: boolean

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download latest model
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: models/
      continue-on-error: true # Don't fail if no model exists yet
      
    - name: Run analysis
      env:
        NEON_CONN_STR: ${{ secrets.NEON_CONN_STR }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "🚀 Starting WinGo Analysis..."
        echo "📊 Configuration:"
        echo "  - Source: db"
        echo "  - Limit: 2000"
        echo "  - Preset: ${{ github.event.inputs.preset || 'balanced' }}"
        echo "  - Max Signals: ${{ github.event.inputs.max_signals || '3' }}"
        echo "  - Fast Mode: ${{ github.event.inputs.enable_fast_mode || 'true' }}"
        echo "  - Ignore Quiet Hours: ${{ github.event.inputs.ignore_quiet_hours || 'false' }}"
        echo "=========================================="
        
        # Check if environment variables are set
        if [ -z "$NEON_CONN_STR" ]; then
          echo "❌ Error: NEON_CONN_STR environment variable not set!"
          exit 1
        fi
        
        if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
          echo "⚠️  Warning: TELEGRAM_BOT_TOKEN not set - alerts will be disabled"
        fi
        
        if [ -z "$TELEGRAM_CHAT_ID" ]; then
          echo "⚠️  Warning: TELEGRAM_CHAT_ID not set - alerts will be disabled"
        fi
        
        echo "🔗 Environment variables checked"
        echo "=========================================="
        echo "⏳ Calculating dynamic wait to align with next period close..."
        NOW_TS=$(date +%s)
        # Compute target epoch = next minute boundary + 11 seconds
        NEXT_MIN=$(( ( (NOW_TS / 60) + 1 ) * 60 ))
        TARGET_TS=$(( NEXT_MIN + 11 ))
        SLEEP_SECS=$(( TARGET_TS - NOW_TS ))
        if [ $SLEEP_SECS -gt 0 ]; then
          echo "🕒 Current: $(date -u +%H:%M:%S) UTC"
          echo "🎯 Target:  $(date -u -d @${TARGET_TS} +%H:%M:%S) UTC (next minute + 11s)"
          echo "😴 Sleeping ${SLEEP_SECS}s to ensure fresh data after period close..."
          sleep ${SLEEP_SECS}
        else
          echo "⚠️ Target already passed; proceeding without extra wait"
        fi
        
        # Build flags from inputs and set fast-mode env for app logic
        FAST_FLAG=$([[ "${{ github.event.inputs.enable_fast_mode }}" == "false" ]] && echo "" || echo "--fast_mode")
        if [[ "${{ github.event.inputs.enable_fast_mode }}" == "false" ]]; then
          export WINGO_FAST_MODE=0
        else
          export WINGO_FAST_MODE=1
        fi
        SLEEP_FLAG=$([[ "${{ github.event.inputs.ignore_quiet_hours }}" == "true" ]] && echo "--disable_sleep_window" || echo "")

        # Run the analyzer with error handling
        python analyze.py \
          --source db \
          --limit 2000 \
          --preset "${{ github.event.inputs.preset || 'balanced' }}" \
          --max_signals "${{ github.event.inputs.max_signals || '3' }}" \
          --enable_alert \
          $FAST_FLAG $SLEEP_FLAG || {
          echo "❌ Analysis failed with exit code $?"
          exit 1
        }
        
        echo "=========================================="
        echo "✅ Analysis completed successfully!"

    - name: Resolve outcomes (adaptive short window)
      if: always()
      env:
        NEON_CONN_STR: ${{ secrets.NEON_CONN_STR }}
        RESOLVE_TIMEOUT_S: 40
        RESOLVE_INTERVAL_S: 5
      run: |
        echo "🔄 Adaptive resolver: trying every ${RESOLVE_INTERVAL_S}s for ${RESOLVE_TIMEOUT_S}s"
        python resolve_wait.py || echo "⚠️ resolve_wait returned non-zero; continuing"
        echo "✅ Outcome resolution step finished"
        
    - name: Upload updated model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
        retention-days: 7